#!/usr/bin/env sh
echo "🔍 Running lint..."
npx eslint packages/*/src/**/*.ts --max-warnings 0
if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Fix errors before committing."
  exit 1
fi
echo "✅ Lint passed"
